In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("e-commerce.csv", encoding='ISO-8859-1')

In [6]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [7]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [9]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [10]:
df.shape

(541909, 8)

In [11]:
# to delete missing values in customer id column 

df=df.dropna(subset=['CustomerID'])

In [12]:
# to remove negetive values
df=df[df['Quantity']>0]

In [13]:
# to remove negetive price
df=df[df['UnitPrice']>0]

In [14]:
# revenue column

df['Revenue']=df['Quantity']*df['UnitPrice']

In [15]:
# date convert

df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 397884 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397884 non-null  object
 1   StockCode    397884 non-null  object
 2   Description  397884 non-null  object
 3   Quantity     397884 non-null  int64
 4   InvoiceDate  397884 non-null  datetime64[ns]
 5   UnitPrice    397884 non-null  float64
 6   CustomerID   397884 non-null  float64
 7   Country      397884 non-null  object
 8   Revenue      397884 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 30.4+ MB

In [17]:

df.nunique()

InvoiceNo      18532
StockCode       3665
Description     3877
Quantity         301
InvoiceDate    17282
UnitPrice        440
CustomerID      4338
Country           37
Revenue         2939
dtype: int64

In [18]:
df['Revenue'].sum()

np.float64(8911407.904)

In [19]:
df['CustomerID'].nunique()

4338

In [20]:
grp=df.groupby('CustomerID').agg({'Revenue':'sum',
                                 'InvoiceNo': 'nunique',
                                  'InvoiceDate': 'max'
                
                                 }).reset_index()

In [21]:
grp.columns=['CustomerID','TotalRevenue','TotalTransactions','LastPurchaseDate']

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 397884 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397884 non-null  object
 1   StockCode    397884 non-null  object
 2   Description  397884 non-null  object
 3   Quantity     397884 non-null  int64
 4   InvoiceDate  397884 non-null  datetime64[ns]
 5   UnitPrice    397884 non-null  float64
 6   CustomerID   397884 non-null  float64
 7   Country      397884 non-null  object
 8   Revenue      397884 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 30.4+ MB

In [23]:
grp.head()

   CustomerID  TotalRevenue  TotalTransactions    LastPurchaseDate
0     12346.0      77183.60                  1 2011-01-18 10:01:00
1     12347.0       4310.00                  7 2011-12-07 15:52:00
2     12348.0       1797.24                  4 2011-09-25 13:13:00
3     12349.0       1757.55                  1 2011-11-21 09:51:00
4     12350.0        334.40                  1 2011-02-02 16:01:00

# RFM Feature Engineering

In [24]:
reference_date=grp['LastPurchaseDate'].max()+pd.Timedelta(days=1)

In [25]:
grp['Recency']=(reference_date - grp['LastPurchaseDate']).dt.days

In [26]:
grp['frequency']=grp['TotalTransactions']

In [27]:
grp['Monetary']=grp['TotalRevenue']

In [28]:
rfm=grp[['CustomerID','Recency','frequency','Monetary']]

In [29]:
rfm.head()

   CustomerID  Recency  frequency  Monetary
0     12346.0      326          1  77183.60
1     12347.0        2          7   4310.00
2     12348.0       75          4   1797.24
3     12349.0       19          1   1757.55
4     12350.0      310          1    334.40

# EDA + Business Insights

In [30]:
top10=rfm.sort_values(by='Monetary',ascending=False).head(10)

In [31]:
top10

      CustomerID  Recency  frequency   Monetary
1689     14646.0        2         73  280206.02
4201     18102.0        1         60  259657.30
3728     17450.0        8         46  194550.79
3008     16446.0        1          2  168472.50
1879     14911.0        1        201  143825.06
55       12415.0       24         21  124914.53
1333     14156.0       10         55  117379.63
3771     17511.0        3         31   91062.38
2702     16029.0       39         63   81024.84
0        12346.0      326          1   77183.60

# Top10 reveneue collection

In [32]:
top10_revenue=top10['Monetary'].sum()
TotalRevenue=rfm['Monetary'].sum()
contribution=(top10_revenue / TotalRevenue)*100

In [33]:
contribution

np.float64(17.261881248972173)

In [34]:
inactive_customer=rfm[rfm['Recency']>90].shape[0]
total_customers=rfm.shape[0]

inactive_percentage=(inactive_customer / total_customers)*100

In [35]:
inactive_percentage

33.40248962655601

# RFM Scoring

In [36]:
rfm['F_score']=pd.qcut(rfm['frequency'],q=5,duplicates='drop')

C:\Users\hp\AppData\Local\Temp\ipykernel_2556\3889367105.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm['F_score']=pd.qcut(rfm['frequency'],q=5,duplicates='drop')

In [37]:
rfm.head()

   CustomerID  Recency  frequency  Monetary       F_score
0     12346.0      326          1  77183.60  (0.999, 2.0]
1     12347.0        2          7   4310.00  (6.0, 209.0]
2     12348.0       75          4   1797.24    (3.0, 6.0]
3     12349.0       19          1   1757.55  (0.999, 2.0]
4     12350.0      310          1    334.40  (0.999, 2.0]

# Monetary Scoring

In [38]:
rfm['M_score']=pd.qcut(rfm['Monetary'],q=5,duplicates='drop')

C:\Users\hp\AppData\Local\Temp\ipykernel_2556\226734607.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rfm['M_score']=pd.qcut(rfm['Monetary'],q=5,duplicates='drop')

In [39]:
rfm.head()

,CustomerID,Recency,frequency,Monetary,F_score,M_score
0,12346.0,326,1,77183.60,"(0.999, 2.0]","(2058.426, 280206.02]"
1,12347.0,2,7,4310.00,"(6.0, 209.0]","(2058.426, 280206.02]"
2,12348.0,75,4,1797.24,"(3.0, 6.0]","(942.276, 2058.426]"
3,12349.0,19,1,1757.55,"(0.999, 2.0]","(942.276, 2058.426]"
4,12350.0,310,1,334.40,"(0.999, 2.0]","(250.194, 490.096]"

In [40]:
rfm[['Monetary','M_score']].head()
rfm['M_score'].value_counts()

M_score
(3.749, 250.194]         868
(490.096, 942.276]       868
(2058.426, 280206.02]    868
(250.194, 490.096]       867
(942.276, 2058.426]      867
Name: count, dtype: int64

# Recency score

In [41]:
rfm['R_score']=pd.qcut(rfm['Recency'],q=5,labels=[5,4,3,2,1],duplicates='drop')

In [42]:
rfm[['Recency','R_score']].head()
rfm['R_score'].value_counts()

R_score
4    904
5    868
1    865
3    858
2    843
Name: count, dtype: int64

# final RFM Score combine

In [43]:
rfm['R_score']=rfm['R_score'].astype(str)
rfm['M_score']=rfm['M_score'].astype(str)
rfm['F_score']=rfm['F_score'].astype(str)

In [44]:
rfm['RFM_Score']=rfm['R_score']+rfm['M_score']+rfm['F_score']

# Basic Segmentation

In [45]:
def segment_customer(row):
    if row['RFM_Score']=='555':
        return 'VIP'
    elif row['F_score']>='4' and row['M_score']>='4':
        return 'Loyal'
    elif row['R_score']=='1':
        return 'At Risk'
    else:
        return 'Regular'

In [46]:
rfm['Segment']=rfm.apply(segment_customer , axis=1)

In [47]:
rfm.head()

,CustomerID,Recency,frequency,Monetary,F_score,M_score,R_score,RFM_Score,Segment
0,12346.0,326,1,77183.60,"(0.999, 2.0]","(2058.426, 280206.02]",1,"1(2058.426, 280206.02](0.999, 2.0]",At Risk
1,12347.0,2,7,4310.00,"(6.0, 209.0]","(2058.426, 280206.02]",5,"5(2058.426, 280206.02](6.0, 209.0]",Regular
2,12348.0,75,4,1797.24,"(3.0, 6.0]","(942.276, 2058.426]",2,"2(942.276, 2058.426](3.0, 6.0]",Regular
3,12349.0,19,1,1757.55,"(0.999, 2.0]","(942.276, 2058.426]",4,"4(942.276, 2058.426](0.999, 2.0]",Regular
4,12350.0,310,1,334.40,"(0.999, 2.0]","(250.194, 490.096]",1,"1(250.194, 490.096](0.999, 2.0]",At Risk

# engagement Score

In [49]:
# normalize recency

rfm['Recency_norm']=(rfm['Recency'].max()-rfm['Recency'])/(rfm['Recency'].max()-rfm['Recency'].min())

In [51]:
# frequency normalize

rfm['frequency_norm']=(rfm['frequency'].max()-rfm['frequency'])/(rfm['frequency'].max()-rfm['frequency'].min())

In [52]:
# Engagement score

rfm['EngagementScore']=(rfm['Recency_norm']+rfm['frequency_norm'])/2

In [53]:
rfm[['Recency','frequency','EngagementScore']].head()

   Recency  frequency  EngagementScore
0      326          1         0.564343
1        2          7         0.984236
2       75          4         0.893593
3       19          1         0.975871
4      310          1         0.585791

# Avg purchase gap

In [54]:
# data Sort

df=df.sort_values(by=['CustomerID','InvoiceDate'])

In [55]:
# previous purchase date

df['PrevDate']=df.groupby('CustomerID')['InvoiceDate'].shift(1)

In [56]:
# gap calculate

df['Gap']=(df['InvoiceDate']-df['PrevDate']).dt.days

In [57]:
# avg gap per customer

avg_gap=df.groupby('CustomerID')['Gap'].mean().reset_index()

In [58]:
# Merge RFM

rfm=rfm.merge(avg_gap , on='CustomerID',how='left')

In [59]:
rfm.head()

,CustomerID,Recency,frequency,Monetary,F_score,M_score,R_score,RFM_Score,Segment,Recency_norm,frequency_norm,EngagementScore,Gap
0,12346.0,326,1,77183.60,"(0.999, 2.0]","(2058.426, 280206.02]",1,"1(2058.426, 280206.02](0.999, 2.0]",At Risk,0.128686,1.000000,0.564343,NaN
1,12347.0,2,7,4310.00,"(6.0, 209.0]","(2058.426, 280206.02]",5,"5(2058.426, 280206.02](6.0, 209.0]",Regular,0.997319,0.971154,0.984236,2.0
2,12348.0,75,4,1797.24,"(3.0, 6.0]","(942.276, 2058.426]",2,"2(942.276, 2058.426](3.0, 6.0]",Regular,0.801609,0.985577,0.893593,9.4
3,12349.0,19,1,1757.55,"(0.999, 2.0]","(942.276, 2058.426]",4,"4(942.276, 2058.426](0.999, 2.0]",Regular,0.951743,1.000000,0.975871,0.0
4,12350.0,310,1,334.40,"(0.999, 2.0]","(250.194, 490.096]",1,"1(250.194, 490.096](0.999, 2.0]",At Risk,0.171582,1.000000,0.585791,0.0

# Customer activity trends

In [61]:
# cutoff date 

cutoff_date=df['InvoiceDate'].max()-pd.Timedelta(days=90)

In [63]:
# recent vs old transaction account

recent=df[df['InvoiceDate']
>
cutoff_date].groupby('CustomerID').size().reset_index(name='RecentTx')


old=df[df['InvoiceDate']<=
cutoff_date].groupby('CustomerID').size().reset_index(name='OldTx')

In [66]:
# Merge

trend=recent.merge(old,on='CustomerID' , how='outer').fillna(0)

In [67]:
# trend

trend['ActivityTrend']=trend['RecentTx']-trend['OldTx']

In [68]:
# merge Rfm

rfm=rfm.merge(trend[['CustomerID','ActivityTrend']],on='CustomerID',how='left')

In [69]:
rfm.head()

,CustomerID,Recency,frequency,Monetary,F_score,M_score,R_score,RFM_Score,Segment,Recency_norm,frequency_norm,EngagementScore,Gap,ActivityTrend
0,12346.0,326,1,77183.60,"(0.999, 2.0]","(2058.426, 280206.02]",1,"1(2058.426, 280206.02](0.999, 2.0]",At Risk,0.128686,1.000000,0.564343,NaN,-1.0
1,12347.0,2,7,4310.00,"(6.0, 209.0]","(2058.426, 280206.02]",5,"5(2058.426, 280206.02](6.0, 209.0]",Regular,0.997319,0.971154,0.984236,2.0,-66.0
2,12348.0,75,4,1797.24,"(3.0, 6.0]","(942.276, 2058.426]",2,"2(942.276, 2058.426](3.0, 6.0]",Regular,0.801609,0.985577,0.893593,9.4,-25.0
3,12349.0,19,1,1757.55,"(0.999, 2.0]","(942.276, 2058.426]",4,"4(942.276, 2058.426](0.999, 2.0]",Regular,0.951743,1.000000,0.975871,0.0,73.0
4,12350.0,310,1,334.40,"(0.999, 2.0]","(250.194, 490.096]",1,"1(250.194, 490.096](0.999, 2.0]",At Risk,0.171582,1.000000,0.585791,0.0,-17.0

# Churn Prediction

In [70]:
rfm['Churn']=(rfm['Recency']>90).astype(int)

In [71]:
rfm['Churn'].value_counts()

Churn
0    2889
1    1449
Name: count, dtype: int64

In [83]:
x= rfm[['Recency','frequency','Monetary','EngagementScore','Gap','ActivityTrend']]
x=x.fillna(0)
y=rfm['Churn']

In [85]:
from sklearn.model_selection import train_test_split
x= rfm[['Recency','frequency','Monetary','EngagementScore','Gap','ActivityTrend']]
x=x.fillna(0)
y=rfm['Churn']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [86]:
x_train.shape
x_test.shape

(868, 6)

# Model 1 Logistic Regression

In [87]:
from sklearn.linear_model import LogisticRegression

model=LogisticRegression()
model.fit(x_train,y_train)

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [88]:
# prediction 

y_pred=model.predict(x_test)

In [89]:
# evaluation

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       561
           1       1.00      1.00      1.00       307

    accuracy                           1.00       868
   macro avg       1.00      1.00      1.00       868
weighted avg       1.00      1.00      1.00       868

In [101]:
import pickle
pickle.dump(model , open('model.pkl','wb'))

In [102]:
import os
os.getcwd()

'C:\\Users\\hp\\first data analyst project'

# Random forest

In [90]:
# import and train

from sklearn.ensemble import RandomForestClassifier

rf_model=RandomForestClassifier(random_state=42)
rf_model.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [93]:
# Prediction

y_pred_rf=rf_model.predict(x_test)

In [94]:
# evaluation

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_rf))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       561
           1       1.00      1.00      1.00       307

    accuracy                           1.00       868
   macro avg       1.00      1.00      1.00       868
weighted avg       1.00      1.00      1.00       868

# XGboost model

In [95]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\users\hp\anaconda3\lib\site-packages (from xgboost) (1.15.3)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/101.7 MB 41.8 kB/s eta 0:40:23
   ---------------------------------------- 0.5/101.7 MB 41.8 kB/s eta 0:40:23
   ---------------------------------------- 0.5/101.7 MB 41.8 kB/s eta 0:40:23
   ---------------------------------------- 0.5/101.7 MB 41.8 kB/s eta 0:40:23
   ---------------------------------------- 0.5/101.7 MB 41.8 kB/s eta 0:40:23
   ---------------------------------------- 0.5/101.7 MB 41.8 kB/s eta 0:40:23
   ---------------------------------------- 0.8/101.7 MB 69.3 kB/s eta 0:24:16
   ---------------------------------------- 0.8/101.7 MB 69.3 kB/s eta 0:24:16
   ---------------------------------------- 0.8/101.7 MB 69.3 kB/s eta 0:24:16
   ---------------------------------------- 0.8/101.7 MB 69.3 kB/s eta 0:24:16
   ---------------------------------------- 0.8/101.7 MB 69.3 kB/s eta 0:24:16
   ---------------------------------------- 0.8/101.7 MB 69.3 kB/s eta 0:24:16
   ---------------------------------------- 0.8/101.7 MB 69.3 kB/s eta 0:24:16
   ---------------------------------------- 0.8/101.7 MB 69.3 kB/s eta 0:24:16
   ---------------------------------------- 0.8/101.7 MB 69.3 kB/s eta 0:24:16
   ---------------------------------------- 0.8/101.7 MB 69.3 kB/s eta 0:24:16
   ---------------------------------------- 0.8/101.7 MB 69.3 kB/s eta 0:24:16
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
   ---------------------------------------- 1.0/101.7 MB 81.3 kB/s eta 0:20:38
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.3/101.7 MB 78.3 kB/s eta 0:21:22
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.6/101.7 MB 76.9 kB/s eta 0:21:42
    --------------------------------------- 1.8/101.7 MB 76.5 kB/s eta 0:21:45
    --------------------------------------- 1.8/101.7 MB 76.5 kB/s eta 0:21:45
    --------------------------------------- 1.8/101.7 MB 76.5 kB/s eta 0:21:45
    --------------------------------------- 1.8/101.7 MB 76.5 kB/s eta 0:21:45
    --------------------------------------- 1.8/101.7 MB 76.5 kB/s eta 0:21:45
    --------------------------------------- 1.8/101.7 MB 76.5 kB/s eta 0:21:45
    --------------------------------------- 1.8/101.7 MB 76.5 kB/s eta 0:21:45
    --------------------------------------- 1.8/101.7 MB 76.5 kB/s eta 0:21:45
    --------------------------------------- 1.8/101.7 MB 76.5 kB/s eta 0:21:45
    --------------------------------------- 1.8/101.7 MB 76.5 kB/s eta 0:21:45
    --------------------------------------- 1.8/101.7 MB 76.5 kB/s eta 0:21:45
    --------------------------------------- 1.8/101.7 MB 76.5 kB/s eta 0:21:45
    --------------------------------------- 1.8/101.7 MB 76.5 kB/s eta 0:21:45
    --------------------------------------- 2.1/101.7 MB 79.1 kB/s eta 0:21:00
    --------------------------------------- 2.1/101.7 MB 79.1 kB/s eta 0:21:00
    --------------------------------------- 2.1/101.7 MB 79.1 kB/s eta 0:21:00
    --------------------------------------- 2.1/101.7 MB 79.1 kB/s eta 0:21:00
    --------------------------------------- 2.1/101.7 MB 79.1 kB/s eta 0:21:00
    --------------------------------------- 2.1/101.7 MB 79.1 kB/s eta 0:21:00
    --------------------------------------- 2.1/101.7 MB 79.1 kB/s eta 0:21:00
    --------------------------------------- 2.1/101.7 MB 79.1 kB/s eta 0:21:00
    --------------------------------------- 2.1/101.7 MB 79.1 kB/s eta 0:21:00
    --------------------------------------- 2.1/101.7 MB 79.1 kB/s eta 0:21:00
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
    --------------------------------------- 2.4/101.7 MB 82.7 kB/s eta 0:20:01
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.6/101.7 MB 82.4 kB/s eta 0:20:03
   - -------------------------------------- 2.9/101.7 MB 90.4 kB/s eta 0:18:13
   - -------------------------------------- 2.9/101.7 MB 90.4 kB/s eta 0:18:13
   - -------------------------------------- 2.9/101.7 MB 90.4 kB/s eta 0:18:13
   - -------------------------------------- 2.9/101.7 MB 90.4 kB/s eta 0:18:13
   - -------------------------------------- 2.9/101.7 MB 90.4 kB/s eta 0:18:13
   - -------------------------------------- 2.9/101.7 MB 90.4 kB/s eta 0:18:13
   - -------------------------------------- 2.9/101.7 MB 90.4 kB/s eta 0:18:13
   - -------------------------------------- 2.9/101.7 MB 90.4 kB/s eta 0:18:13
   - -------------------------------------- 2.9/101.7 MB 90.4 kB/s eta 0:18:13
   - -------------------------------------- 2.9/101.7 MB 90.4 kB/s eta 0:18:13
   - -------------------------------------- 2.9/101.7 MB 90.4 kB/s eta 0:18:13
   - -------------------------------------- 2.9/101.7 MB 90.4 kB/s eta 0:18:13
   - -------------------------------------- 2.9/101.7 MB 90.4 kB/s eta 0:18:13
   - -------------------------------------- 2.9/101.7 MB 90.4 kB/s eta 0:18:13
   - -------------------------------------- 3.1/101.7 MB 90.0 kB/s eta 0:18:16
   - -------------------------------------- 3.1/101.7 MB 90.0 kB/s eta 0:18:16
   - -------------------------------------- 3.1/101.7 MB 90.0 kB/s eta 0:18:16
   - -------------------------------------- 3.1/101.7 MB 90.0 kB/s eta 0:18:16
   - -------------------------------------- 3.1/101.7 MB 90.0 kB/s eta 0:18:16
   - -------------------------------------- 3.1/101.7 MB 90.0 kB/s eta 0:18:16
   - -------------------------------------- 3.1/101.7 MB 90.0 kB/s eta 0:18:16
   - -------------------------------------- 3.1/101.7 MB 90.0 kB/s eta 0:18:16
   - -------------------------------------- 3.1/101.7 MB 90.0 kB/s eta 0:18:16
   - -------------------------------------- 3.1/101.7 MB 90.0 kB/s eta 0:18:16
   - -------------------------------------- 3.1/101.7 MB 90.0 kB/s eta 0:18:16
   - -------------------------------------- 3.1/101.7 MB 90.0 kB/s eta 0:18:16
   - -------------------------------------- 3.1/101.7 MB 90.0 kB/s eta 0:18:16
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.4/101.7 MB 82.9 kB/s eta 0:19:45
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.7/101.7 MB 83.2 kB/s eta 0:19:39
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 3.9/101.7 MB 83.9 kB/s eta 0:19:25
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04
   - -------------------------------------- 4.2/101.7 MB 85.2 kB/s eta 0:19:04

In [96]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xgb_model.fit(x_train, y_train)

C:\Users\hp\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [22:48:16] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [97]:
# Prediction 

y_pred_xgb = xgb_model.predict(x_test)

In [98]:
# evaluation

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       561
           1       1.00      1.00      1.00       307

    accuracy                           1.00       868
   macro avg       1.00      1.00      1.00       868
weighted avg       1.00      1.00      1.00       868

In [99]:
# comparison of model 

from sklearn.metrics import f1_score

# Logistic Regression
f1_lr = f1_score(y_test, y_pred)

# Random Forest
f1_rf = f1_score(y_test, y_pred_rf)

# XGBoost
f1_xgb = f1_score(y_test, y_pred_xgb)

print("Logistic Regression F1:", f1_lr)
print("Random Forest F1:", f1_rf)
print("XGBoost F1:", f1_xgb)

Logistic Regression F1: 0.9983739837398374
Random Forest F1: 1.0
XGBoost F1: 1.0

In [100]:
import pandas as pd

results = pd.DataFrame({
    'Model': ['Logistic Regression', 'Random Forest', 'XGBoost'],
    'F1 Score': [f1_lr, f1_rf, f1_xgb]
})

print(results)

                 Model  F1 Score
0  Logistic Regression  0.998374
1        Random Forest  1.000000
2              XGBoost  1.000000